import { describe, expect, it } from 'vitest';
import {
  ActionList,
  AlertDialog,
  Autocomplete,
  Avatar,
  AvatarGroup,
  Button,
  ButtonGroup,
  Card,
  Caption,
  Checkbox,
  CheckboxGroup,
  Chip,
  CodeBlock,
  Combobox,
  ContextMenu,
  IconButton,
  Input,
  Link,
  Menu,
  MultiSelect,
  NumberInput,
  Overline,
  Popover,
  Radio,
  RadioGroup,
  SearchInput,
  Select,
  Separator,
  Slider,
  Switch,
  Table,
  Tabs,
  TextField,
  TextArea,
  Tooltip,
  ToggleButton,
  ToggleButtonGroup,
  Typography,
  Underline,
} from './index';

describe('Base UI export coverage', () => {
  it('exports the approved core component set', () => {
    expect(ActionList).toBeTruthy();
    expect(AlertDialog).toBeTruthy();
    expect(Autocomplete).toBeTruthy();
    expect(Avatar).toBeTruthy();
    expect(AvatarGroup).toBeTruthy();
    expect(Button).toBeTruthy();
    expect(ButtonGroup).toBeTruthy();
    expect(Card).toBeTruthy();
    expect(Caption).toBeTruthy();
    expect(Checkbox).toBeTruthy();
    expect(CheckboxGroup).toBeTruthy();
    expect(Chip).toBeTruthy();
    expect(CodeBlock).toBeTruthy();
    expect(Combobox).toBeTruthy();
    expect(ContextMenu).toBeTruthy();
    expect(IconButton).toBeTruthy();
    expect(Input).toBeTruthy();
    expect(Link).toBeTruthy();
    expect(Menu).toBeTruthy();
    expect(MultiSelect).toBeTruthy();
    expect(NumberInput).toBeTruthy();
    expect(Overline).toBeTruthy();
    expect(Popover).toBeTruthy();
    expect(Radio).toBeTruthy();
    expect(RadioGroup).toBeTruthy();
    expect(SearchInput).toBeTruthy();
    expect(Select).toBeTruthy();
    expect(Separator).toBeTruthy();
    expect(Slider).toBeTruthy();
    expect(Switch).toBeTruthy();
    expect(Table).toBeTruthy();
    expect(Tabs).toBeTruthy();
    expect(TextField).toBeTruthy();
    expect(TextArea).toBeTruthy();
    expect(Tooltip).toBeTruthy();
    expect(ToggleButton).toBeTruthy();
    expect(ToggleButtonGroup).toBeTruthy();
    expect(Typography).toBeTruthy();
    expect(Underline).toBeTruthy();
  });
});
