import type { ComponentType } from 'react';
import {
  LuCircle,
  LuLoader,
  LuPause,
  LuCircleCheck,
  LuCircleX,
  LuCircleDashed,
  LuCircleDot,
  LuUser,
  LuSparkles,
  LuSettings,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuArrowDown,
  LuCopy,
  LuLock,
  LuTrendingUp,
  LuTrendingDown,
  LuMinus,
  LuRefreshCw,
  LuPencil,
  LuThumbsUp,
  LuThumbsDown,
  LuSquare,
  LuCornerDownRight,
  LuFile,
  LuWrench,
  LuDatabase,
  LuTriangleAlert,
  LuMessageSquare,
  LuPlus,
  LuBot,
  LuImage,
  LuX,
  LuCoins,
  LuBox,
  LuScrollText,
  LuGlobe,
  LuShare2,
  LuGitBranch,
  LuTrash2,
  LuGauge,
  LuClock,
  LuZap,
  LuShieldCheck,
} from 'react-icons/lu';
import type { AgentStatus, ToolCallStatus, StepStatus, ChatRole } from './types';

type IconComponent = ComponentType<{ size?: number | string; className?: string }>;

export const AGENT_STATUS_ICONS: Record<AgentStatus, IconComponent> = {
  idle: LuCircle,
  running: LuLoader,
  paused: LuPause,
  complete: LuCircleCheck,
  error: LuCircleX,
};

export const TOOL_STATUS_ICONS: Record<ToolCallStatus, IconComponent> = {
  pending: LuCircleDashed,
  running: LuLoader,
  success: LuCircleCheck,
  error: LuCircleX,
};

export const STEP_STATUS_ICONS: Record<StepStatus, IconComponent> = {
  pending: LuCircleDashed,
  active: LuCircleDot,
  complete: LuCircleCheck,
  error: LuCircleX,
};

export const CHAT_ROLE_ICONS: Record<ChatRole, IconComponent> = {
  user: LuUser,
  assistant: LuBot,
  system: LuSettings,
};

export {
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuArrowDown,
  LuCopy,
  LuLock,
  LuTrendingUp,
  LuTrendingDown,
  LuMinus,
  LuRefreshCw,
  LuPencil,
  LuThumbsUp,
  LuThumbsDown,
  LuSquare,
  LuCornerDownRight,
  LuFile,
  LuWrench,
  LuDatabase,
  LuTriangleAlert,
  LuMessageSquare,
  LuPlus,
  LuBot,
  LuImage,
  LuX,
  LuCoins,
  LuBox,
  LuScrollText,
  LuGlobe,
  LuLoader,
  LuUser,
  LuSparkles,
  LuSettings,
  LuShare2,
  LuGitBranch,
  LuTrash2,
  LuGauge,
  LuClock,
  LuZap,
  LuShieldCheck,
};
