import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PREFIXES = ['color', 'syntax', 'terminal'] as const;
type Prefix = (typeof PREFIXES)[number];

export interface ExtractedKeys {
  colors: string[];
  syntax: string[];
  terminal: string[];
}

const VAR_RE = /--ov-([a-z]+)-([a-z0-9-]+)\s*:/g;

export function extractTokenKeys(css: string): ExtractedKeys {
  const buckets: Record<Prefix, Set<string>> = {
    color: new Set(),
    syntax: new Set(),
    terminal: new Set(),
  };
  for (const match of css.matchAll(VAR_RE)) {
    const prefix = match[1] as Prefix;
    const rest = match[2];
    if (!PREFIXES.includes(prefix) || rest === undefined) continue;
    // Convert hyphens to dots to produce the dotted token key form.
    buckets[prefix].add(`${prefix}.${rest.replaceAll('-', '.')}`);
  }
  return {
    colors: Array.from(buckets.color).sort(),
    syntax: Array.from(buckets.syntax).sort(),
    terminal: Array.from(buckets.terminal).sort(),
  };
}

export function renderTypesFile(keys: ExtractedKeys): string {
  const union = (items: string[]) =>
    items.length === 0 ? 'never' : items.map((k) => `  | '${k}'`).join('\n');
  return `// AUTO-GENERATED by scripts/generate-token-keys.ts. Do not edit by hand.
// Regenerate with: pnpm generate:token-keys

export type ColorTokenKey =
${union(keys.colors)};

export type SyntaxTokenKey =
${union(keys.syntax)};

export type TerminalTokenKey =
${union(keys.terminal)};

export const COLOR_TOKEN_KEYS: ReadonlySet<ColorTokenKey> = new Set([
${keys.colors.map((k) => `  '${k}',`).join('\n')}
]) as ReadonlySet<ColorTokenKey>;

export const SYNTAX_TOKEN_KEYS: ReadonlySet<SyntaxTokenKey> = new Set([
${keys.syntax.map((k) => `  '${k}',`).join('\n')}
]) as ReadonlySet<SyntaxTokenKey>;

export const TERMINAL_TOKEN_KEYS: ReadonlySet<TerminalTokenKey> = new Set([
${keys.terminal.map((k) => `  '${k}',`).join('\n')}
]) as ReadonlySet<TerminalTokenKey>;
`;
}

function main() {
  const here = resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
  const input = readFileSync(resolve(here, 'src/theme/styles.css'), 'utf8');
  const output = resolve(here, 'src/theme/generated/tokenKeys.ts');
  const keys = extractTokenKeys(input);
  const content = renderTypesFile(keys);
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, content, 'utf8');
  console.log(
    `Generated ${output} (${keys.colors.length} color, ${keys.syntax.length} syntax, ${keys.terminal.length} terminal)`,
  );
}

// ESM-compatible entrypoint guard: only run main() when executed directly via tsx/node.
// import.meta.url is the file's URL; process.argv[1] is the executed file path.
if (import.meta.url === new URL(process.argv[1] ?? '', 'file:').href) {
  main();
}
